import type { NewsCategory, NewsItem } from "@/components/next-dashboard/calendar/newsFeedTypes";

export const NEWS_CATEGORIES: Array<{ id: "all" | NewsCategory; label: string }> = [
  { id: "all", label: "All Categories" },
  { id: "Geopolitics", label: "Geopolitics" },
  { id: "Equities", label: "Equities" },
  { id: "Commodities", label: "Commodities" },
  { id: "Rates", label: "Rates" },
  { id: "FX", label: "FX" },
  { id: "Macro", label: "Macro" },
  { id: "Central Banks", label: "Central Banks" },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: "n1",
    unread: true,
    timeLabel: "01:15",
    source: "ZEROHEDGE",
    category: "Geopolitics",
    headline: "China Warns of Retaliation After U.S. Announces Additional Tariffs",
    impact: "high",
    instruments: ["USD", "SPY"],
    articleUrl: "https://www.zerohedge.com/",
    publishedAgo: "3h ago",
    summary:
      "China signaled countermeasures after the U.S. introduced new tariffs on strategic imports. The move renewed concerns around global growth and supply-chain volatility. Risk sentiment turned cautious as investors rotated into defensive exposures.",
    keyPoints: [
      "Commerce ministry vowed targeted response to new tariffs.",
      "Markets repriced trade-risk premium in cyclicals and industrials.",
      "USD firmed as global growth uncertainty increased.",
      "Rates moved lower on safe-haven demand.",
    ],
    regimeImpact: "BEARISH VALUE — increases safe-haven demand and pressures cyclicals.",
    fredSeries: [
      { code: "BOPGSTB", name: "Balance of Payments: Goods Balance" },
      { code: "USIRTR", name: "Effective Federal Funds Rate" },
      { code: "CPIAUCSL", name: "Consumer Price Index for All Urban Consumers" },
      { code: "DGS10", name: "10-Year Treasury Constant Maturity" },
    ],
  },
  {
    id: "n2",
    unread: true,
    timeLabel: "00:47",
    source: "REUTERS",
    category: "Central Banks",
    headline: "Fed's Policy Well Positioned, No Rush to Cut Rates",
    impact: "medium",
    instruments: ["USD", "TLT"],
    articleUrl: "https://www.reuters.com/",
    publishedAgo: "4h ago",
    summary: "Fed officials reiterated patience and emphasized data dependence. Markets trimmed near-term cut odds.",
    keyPoints: ["Forward guidance stayed restrictive.", "Front-end yields rose modestly.", "USD outperformed low-yield peers."],
    regimeImpact: "NEUTRAL MACRO — reinforces current restrictive baseline.",
    fredSeries: [{ code: "FEDFUNDS", name: "Federal Funds Effective Rate" }],
  },
  {
    id: "n3",
    unread: true,
    timeLabel: "00:32",
    source: "BLOOMBERG",
    category: "Equities",
    headline: "S&P 500 Futures Rise on Tech Strength; Nvidia Jumps on AI Demand",
    impact: "medium",
    instruments: ["SPY"],
    articleUrl: "https://www.bloomberg.com/",
    publishedAgo: "5h ago",
    summary: "Mega-cap tech led risk appetite higher in premarket trading.",
    keyPoints: ["Semiconductor names outperformed.", "Breadth remained mixed.", "Volatility stayed contained."],
    regimeImpact: "BULLISH RISK ON — supports growth leadership.",
    fredSeries: [{ code: "SP500", name: "S&P 500 Index" }],
  },
  {
    id: "n4",
    unread: true,
    timeLabel: "00:18",
    source: "WSJ",
    category: "Rates",
    headline: "Treasury Yields Steady Ahead of Key Inflation Data",
    impact: "low",
    instruments: ["TLT", "USD"],
    articleUrl: "https://www.wsj.com/",
    publishedAgo: "6h ago",
    summary: "Rates traders stayed defensive ahead of CPI revisions.",
    keyPoints: ["2s10s curve unchanged.", "Real yields held recent highs."],
    regimeImpact: "NEUTRAL VALUE — awaiting inflation confirmation.",
    fredSeries: [{ code: "T10Y2Y", name: "10Y-2Y Treasury Spread" }],
  },
  {
    id: "n5",
    unread: true,
    timeLabel: "00:05",
    source: "KITCO",
    category: "Commodities",
    headline: "Gold Holds Above $2,400 as Geopolitical Risks Support Rally",
    impact: "medium",
    instruments: ["GLD", "USD"],
    articleUrl: "https://www.kitco.com/",
    publishedAgo: "7h ago",
    summary: "Gold retained bid tone on elevated geopolitical uncertainty.",
    keyPoints: ["ETF flows turned positive.", "Real-rate sensitivity remained high."],
    regimeImpact: "BULLISH DEFENSIVE — supports hedge demand.",
    fredSeries: [{ code: "GOLDAMGBD228NLBM", name: "Gold Fixing Price" }],
  },
];
